[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://145.241.159.235.nip.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
