// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXiH4OxKMvUea1LN1HsQEzjh1lrgRNvM',
    appId: '1:92139939502:web:fa42f40c4e94fa204c2f3f',
    messagingSenderId: '92139939502',
    projectId: 'dpeoij',
    authDomain: 'dpeoij.firebaseapp.com',
    storageBucket: 'dpeoij.firebasestorage.app',
    measurementId: 'G-LK8JJTYK1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSl21NLE4aCFYkFPg2evB7QebWbOXWCk',
    appId: '1:92139939502:android:bb633e846a512d154c2f3f',
    messagingSenderId: '92139939502',
    projectId: 'dpeoij',
    storageBucket: 'dpeoij.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiz0CZoEGt0yZa9lEy3RnNAtpzsd_9vyk',
    appId: '1:92139939502:ios:a4a676e6f59d8aa14c2f3f',
    messagingSenderId: '92139939502',
    projectId: 'dpeoij',
    storageBucket: 'dpeoij.firebasestorage.app',
    iosBundleId: 'com.psyche.kelivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiz0CZoEGt0yZa9lEy3RnNAtpzsd_9vyk',
    appId: '1:92139939502:ios:a4a676e6f59d8aa14c2f3f',
    messagingSenderId: '92139939502',
    projectId: 'dpeoij',
    storageBucket: 'dpeoij.firebasestorage.app',
    iosClientId: '92139939502-qgqcodld4m9lv3o44bs9jpcbtf071jf0.apps.googleusercontent.com',
    iosBundleId: 'com.psyche.kelivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmXiH4OxKMvUea1LN1HsQEzjh1lrgRNvM',
    appId: '1:92139939502:web:000ec8b89de13b4f4c2f3f',
    messagingSenderId: '92139939502',
    projectId: 'dpeoij',
    authDomain: 'dpeoij.firebaseapp.com',
    storageBucket: 'dpeoij.firebasestorage.app',
    measurementId: 'G-TSHY6SVBDF',
  );

}